name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master

jobs:
  # 编译和构建 Docker Image
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 登录 Docker Registry
      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build \
            --cache-from=${{ vars.DOCKER_REGISTRY }}/hello-world:latest \
            -t ${{ vars.DOCKER_REGISTRY }}/hello-world:latest .

      # 4. 推送 Docker 镜像
      - name: Push Docker image
        run: docker push ${{ vars.DOCKER_REGISTRY }}/hello-world:latest

  # 重新部署 Image
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 5. 登录服务器重新部署
      - name: Executing remote ssh commands using private key
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ vars.PATH }}
            sudo docker compose down
            sudo docker compose pull
            sudo docker compose up -d --remove-orphans